name: rick_morty
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  dio: ^5.5.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  get_it: ^8.2.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
